### ISSUE TITLE
Testing environment code: .....eeeeee.....s......eeeeeeee

### ISSUE THREAD

**Issue by codegenes99** [dunbarcyber/cyphon#109]
Good day. 
I set up and installed Ubuntu on a Dell Latitude e7250 i7-5600 @ 2.60GHz with 16gb of memory laptop, followed the directions from http://cyphon.readthedocs.io/en/latest/getting-started/getting-started.html; But after going to step: Starting Docker Containers --> Development Environment ---> Testing Environment and inputting the following code from the instruction set: 
$ cd /opt/cyphon/cyphondock
$ sudo docker-compose -f docker-compose.travis.yml up -d
$ sudo docker exec cyphondock_cyphon_1 python manage.py test --noinput

My terminal sat for a couple hours with only ".......eeee......." on the screen by the 4th hour the terminal output of the Testing Command was at "...............eeeeee.....s.....eeeeeee...........," at which time I performed CTRL +C and my terminal went back to sudo. I then performed the next 2 steps in the list: Loading Basic Settings and Creating a Superuser without any problem. 

Can anyone shine some light on why my terminal sat for so long without indicator of progress, or why it did not complete its testing and return to sudo. 

Thanks, this is the first time I have installed Cyphon and I am fairly new to Linux, so my verbiage may not be industry.

**Comment by lhadjchikh** [comment]
The tests definitely shouldn't take that long to run (they usually only take a few minutes). Each "e" stands for an error that occurred during a test, each dot is a successful test, an "s" is a skipped test, and an "f" is a failed test. If you run the tests using the `--verbosity=2` setting, you can at least see where the tests are getting hung up or throwing errors. Unfortunately, it won't give you details about the errors until all the tests finish.

I suspect the problem is with the functional tests (which require a web driver), but it's hard to tell without a stack trace. We weren't able to reproduce this problem on a fresh install, so it's hard to say what's going on. You can try the `docker-compose up` command without the `-d` flag, so you can see the log output (and run tests in a different terminal), or you can check the log files in Kibana (which should be capturing container logs that were gathered by Logspout).

If everything else is working okay, I wouldn't worry too much about the tests. The instructions on the testing environment are just there for folks who want to work on the codebase. I'll move them to the Developer Guide so it doesn't trip up anyone who's just trying to get a basic install going. However, if you're able to find more details about the errors, or if you run into any other problems, please let us know!

**Comment by codegenes99** [comment]
The information you have provided has helped me clarify what was occurring during the installation and testing. As this is my first time installing Cyphon and its components, have a forum/support group will greatly help me in the future. I plan on finding a web driver as your recommended and re-test, hoping I can get this software up and running. 

Thanks again for your time

**Comment by lhadjchikh** [comment]
No problem! The strange thing is, the functional tests should be skipped automatically if they can't find a web driver (and the Selenium container in the `docker-compose.travis.yml` file should be providing that in any case). You could try this instead:

    $ sudo docker-compose -f docker-compose.yml up -d
    $ sudo docker exec cyphondock_cyphon_1 python manage.py test --noinput --verbosity=2

This will start the production environment instead, and it *should* skip the functional tests. You could also try this with the development environment, if you prefer.

**Comment by codegenes99** [comment]
Thanks for the assistance. I ran the following commands that your provided and the action completed 1123 tests in 211.719s which is the resolution that I was looking for.
$ cd /opt/cyphon/cyphondock
$ sudo docker-compose -f docker-compose.yml up -d
$ sudo docker exec cyphondock_cyphon_1 python manage.py test --noinput --verbosity=2

But after running the next command for:Loading Basic Setting 
$ sudo docker exec cyphondock_cyphon_1 python manage.py loaddata fixtures/starter-fixtures.json
------Result $: command not found

Creating a Superuser:
$ sudo docker exec -it cyphondock_cyphon_1 /bin/sh
-------Result: rpc error: code = 2 desc = oci runtime error:
 exec failed: container_linux.go:247: starting container process caused "exec: \"/bin/s\": stat /bin/s: no such file or directory"

python manage.py createsuperuser
python: can't open file 'manage.py': [Errno 2] No such file or directory

When I ran those commands before the above two commands for Loading Basic commands and Creating a SuperUser returned with zero errors. Now they are returning errors...

**Comment by lhadjchikh** [comment]
Is there any chance the last character was missing from the `sudo docker exec -it cyphondock_cyphon_1 /bin/sh` command you ran? It looks like it was looking for `/bin/s` instead of `/bin/sh`.

It's also possible some settings got messed up in the containers you currently have, so I would run `sudo docker-compose down` to remove those containers, and run `sudo docker ps -a` to confirm that no cyphondock containers are still around. Then try `sudo docker-compose up -d` again.

**Comment by codegenes99** [comment]
Thanks for pointing that out to me, as a newbie I made a simple mistake. It appears I have run all the installation commands. Now on to find the instructions on getting the GUI interface to show up, so that I can log in on my Ubuntu machine, 

Thanks for help

**Comment by lhadjchikh** [comment]
No worries; I've made the exact same mistake myself on more than one occasion! :-)

If you're running the production environment, you should be able to access the GUI on port 80. Here's the relevant section of the docs: http://cyphon.readthedocs.io/en/latest/getting-started/start-docker.html#ports

**Comment by codegenes99** [comment]
Thanks for the assistance. Followed information. Started Cyphon / Docker from the terminal, went to my browser and the appropriate port. Found the GUI log in screen, logged in with email and password. But after logging in I get a blank White Screen, with no content. I must have missed something. The URL/URI only shows localhost/app...hmmm....

**Comment by lhadjchikh** [comment]
Hmm... Can you access localhost/admin? That would be the admin page.

You can also check if Kibana is up (port 5601 in production). If so, you can use that to check logs for errors in the logspout-* index.

**Comment by codegenes99** [comment]
Yes... I forget to install the Firefox certs, installed them. And went to localhost/admin and the log in screen was there with all the information. Now back to re-read all the information so that I can play with this in my environment. You have been a BIG help. Thanks :)

**Comment by codegenes99** [comment]
Good day, 
To get the most out of resources. Would you suggest keeping cyphon/docker running 24/7 or only when needed. Reason I ask, is I had success yesterday getting cyphon/docker running and was able to log into the GUI. 

But after shutting down cyphon/docker and the PC last night, I arrived this next morning, signed into Ubuntu and ran terminal to turn on cyphon/docker with following commands.
$ cd /opt/cyphon/cyphondock
$ sudo docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

And my results: "cyphondock_filebeat_1 exited with code 1" and Local/Admin is stating "This Site Can't be reached" "localhost refused to connect... Yes, I do have network connection.
Thanks

**Comment by lhadjchikh** [comment]
With regard to the Filebeat error, it looks like you need to change the permissions on the `config/beats/filebeat/filebeat.yml` file. If you're in the `cyphondock` working directory, you can run this command:

    sudo chmod go-w config/beats/filebeat

Filebeat is optional, though. If you're not actually using it to monitor logs on your host, you can just comment out all references to it in `docker-compose.yml`.

I'm not sure what's causing the connection issue, though. Cyphon is meant to be running all the time, but restarting it shouldn't case an error. You could try `sudo docker-compose down` and try to restart it again. You can also check Kibana for any error messages associated with the `cyphondock_cyphon_1` or `cyphondock_nginx_1` containers.

**Comment by codegenes99** [comment]
Thanks, I will try this. I first step up cyphon on a laptop. But once I have all the bug/glitches worked out and am comfortable with the software it will be installed on a desktop/server which can be left on. The machine will also more hard-drive space.
