### ISSUE TITLE
monitor not functioning

### ISSUE THREAD

**Issue by adamstauffer** [dunbarcyber/cyphon#172]
I have a monitor created for my Nessus distillery (elasticsearch.nessus.nessus). The monitor is showing as down even though there is data and alerts within the timeframe I specified. Here is how the monitor is currently configured:

* name - monitor_nessus
* groups - None
* enabled - True
* distilleries - elasticsearch.nessus.nessus
* time interval - 1
* time unit - days
* alerts enabled - True
* repeating alerts - False
* alert level - Critical

The monitor shows no data (no last alert, no recent data) despite there being data in the Elasticsearch index and even alerts in this distillery from today. I have a monitor for twitter data that is functioning properly

**Comment by lhadjchikh** [comment]
You probably need to tweak your Logstash configuration to send an extra copy of the documents to RabbitMQ. Monitors were originally designed to update themselves when a document is saved by a distillery (i.e., within Cyphon), so they rely on document-saved signals rather than polling. For cases in which the data is sent directly to Elasticsearch through Logstash, you'll need to use [this workaround](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/3-output.conf#L46-L60), which involves sending another copy of the documents to RabbitMQ, where they can be processed using the [receiver](http://cyphon.readthedocs.io/en/latest/modules/receiver.html) package. Try adding "nessus" to the list of document types that are being sent to the "monitors" queue in the RabbitMQ output, like so:
```
    if [type] in ["http", "snort", "nessus"] {
        rabbitmq {
            host => "rabbit"
            port => 5672
            exchange => "cyphon"
            exchange_type => "direct"
            key => "monitors"
            user => "guest"
            password => "guest"
            vhost => "cyphon"
            durable => true
            persistent => true
        }
    }
```

**Comment by adamstauffer** [comment]
yep that fixed it thx
