### ISSUE TITLE
Create custom taste for mapping different bottle fields

### ISSUE THREAD

**Issue by robinlennox** [dunbarcyber/cyphon#222]
It would be useful to map two differently name bottle fields which have the same data from logs to a universal taste in Cyphon.

For example:
Log1 has a field called custom_time
Log2 has a field called customtime

If I could map these two bottle fields to a universal one such as custom_time in taste it would save me having to parse all the data before it gets into Cyphon.

**Comment by lhadjchikh** [comment]
DataCondensers are meant to do this sort of field mapping (as described [here](http://cyphon.readthedocs.io/en/latest/user-manual/data-processing.html#step-2-configure-a-condenser)), but they only work if Cyphon is saving the data (a "schema-on-write" setup). 

I think perhaps what you're suggesting is more of a "schema-on-read" setup, in which fields could be interpreted in a specific way, regardless of how they've been saved. I actually have this in our backlog, but it will a major overhaul of some core packages. Maybe something for Cyphon 2.0 or 3.0?

Tastes do a schema-on-read in a very limited way. If you have one Container with a field `custom_time` and another Container with a field `customtime`, each would have their own Taste that identifies that field as the "datetime" field for that Container. This allows Cyphon to perform operations on the data, by knowing which field to interpret as a datetime. Tastes are defined per Container, so there's a one-to-one relationship between Containers and Tastes.

To define Tastes based on fields (rather than Containers) would be more complicated. In addition to fields with different names that have the same meaning, as in your example, the same field can also have different meanings in different Containers. For example, a field called `name` could represent an "author" in one Container and a "title" in a different container. This means there would be a many-to-many relationship between fields and their possible meanings. So, you'd still need to know what Container a field was in to know what that field meant. This is why each Container gets its own Taste in the current architecture.

Hopefully that explains the rationale for doing things this way, but a more general schema-on-read implementation would definitely be cool, and it's something I want to give more thought to as the project evolves. :-)
