### ISSUE TITLE
Can't display Locations

### ISSUE THREAD

**Issue by santi10** [dunbarcyber/cyphon#464]
Hi,

Main web doesn't show me the location map. I see this massege "Can't display map. Missing CYCLOPS.MAPBOX_ACCESS_TOKEN in Cyphon configuration."

Do you know this messages, please? May you help me, please?

Thx

**Comment by chasepbrewer** [comment]
Did you sign up for a mabox access token and set it in your `conf.py` settings, outlined [here](http://cyphon.readthedocs.io/en/latest/getting-started/configure-project.html?highlight=mapbox#cyclops)?

**Comment by santi10** [comment]
Hi,

I set this


CYCLOPS = {
    'ENABLED': True,
    'MAPBOX_ACCESS_TOKEN': '',
    'DEVELOPMENT_ENABLED': False,
    'DEVELOPMENT_URL': 'http://localhost:8080/',
}


is it correct?

**Comment by chasepbrewer** [comment]
No that's just the visual example of the what the settings look like in `conf.py` so you can spot them more easily. Directly below that example you'll see the instructions for signing up for a mapbox access token:

`In order to show maps with locations and get geolocation data, you can sign up for a mapbox access token here and place it as MAPBOX_ACCESS_TOKEN.`

You go to this link: https://www.mapbox.com/studio/signup/. Sign up for an access token, then set that access token on `MAPBOX_ACCESS_TOKEN`. You should be able to see maps after that.

**Comment by santi10** [comment]
Yes, I've added this tokken but I follow without show it (map location)...Also I restarted the virtual machine and nothing. What i can do, please? Thx

**Comment by santi10** [comment]
Sorry, I didn't commit the changes on docker image. All done! Thx
