### ISSUE TITLE
Send syslog to Cyphon

### ISSUE THREAD

**Issue by santi10** [dunbarcyber/cyphon#467]
Hi,

I'm trying send a new log via syslog to Cyphon...but I don't set it. I want to explain my site is:

My vm linyx wiht syslog (syslog ng) is sending the logs via syslog to Cyphon...What I must do but that Cyphon received this events?????

Thanks
Santi

**Comment by santi10** [comment]
Hi, could you help me, please?

**Comment by fatalglitch** [comment]
Are you using the CyphonDock docker configurations we provided

**Comment by fatalglitch** [comment]
@santi10 Are you using the CyphonDock docker configurations or building your own stack?

For Cyphon to accept syslog, the easiest method is to send the syslog data to Logstash, and then Logstash to Cyphon's RabbitMQ instances, which can then be ingested by the Cyphon WatchDogs based on Data Sieves and Rules.

This will allow you to also write the syslog data to Elasticsearch for long term storage, as well as only alert based on the Data Rules setup within Cyphon

**Comment by santi10** [comment]
Hi fatalglitch,

Yes, I'm using the cyphondock (iso). I'm sending logs to Cyphondock but I don't see the port udp 514 up...If I check the config logstash, I see the port beats and port 5000 tcp (into into file input). Do I must config the line "input udp port 514" on file input? Thank to you!

**Comment by fatalglitch** [comment]
You need to add something similar to below to your logstash configuration, in order to receive the syslog data. The grok patterns need to match the format of your incoming log messages in order for them to be properly ingested.

`
input {

  tcp {
      port => 1514
      type => syslog
  }

}


filter {
  if [type] == "syslog" {

    ## This is an example pattern, and will NOT work for your syslog message
    grok {
      match => { "message" => "(?<alert_id><\d\d\d>)\[(?<mac_addr>([A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}))\]\sAPB0C745CF744A\s:?\s?(?<alert_type>([A-Za-z]*)):\s%{GREEDYDATA}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }

    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }

  }
}



output {

## OPTIONAL/Alternate to writing to Elasticsearch direct
## This will send a subset of events to Cyphon LogChutes for parsing
## instead of writing directly to Elasticsearch
# if [type] == "syslog" {
#     rabbitmq {
#         host => "rabbit"
#         port => 5672
#         exchange => "cyphon"
#         exchange_type => "direct"
#         key => "logchutes"
#         user => "guest"
#         password => "guest"
#         vhost => "cyphon"
#         durable => true
#         persistent => true
#     }
# }

  ##################################################
  # Send to Elasticsearch for storage and indexing #
  ##################################################

  if [type] == "syslog" {
    elasticsearch {
      hosts => ["elasticsearch"]
      index => "syslog-%{+YYYY-MM-dd}"
      document_id => "%{@uuid}"
      sniffing => false
    }
  }

  ######################################################
  # Send to RabbitMQ for ingestion by Cyphon Watchdogs #
  ######################################################

  if [type] in ["syslog"] {
      rabbitmq {
          host => "rabbit"
          port => 5672
          exchange => "cyphon"
          exchange_type => "direct"
          key => "watchdogs"
          user => "guest"
          password => "guest"
          vhost => "cyphon"
          durable => true
          persistent => true
      }
  }

}
`

**Comment by fatalglitch** [comment]
Once this is running, you need to make sure you create the bottles, labels, etc. for this dataset in Cyphon, and setup a watchdog to create the alerts based on the data rules

**Comment by ziednamouchi** [comment]
I think that port 514 wont work since it needs logstash to run as root. You can try another port which is greater than 1024, allow cyphondock logstash to map it to the system port by adding a line to the docker-compose.override under logstash ports section.
I'm not sure this will work. I used this method with many log sources and it worked for me but when I tried it with syslog it did not work.
keep us updated if any method works for you.
thanks
