### ISSUE TITLE
Docker image Cyphon...What else?

### ISSUE THREAD

**Issue by santi10** [dunbarcyber/cyphon#501]
Hi,

I set my ubuntu 16.04 with docker ce. 

I've started docker image "dunbar/cyphon", and "ps -a":

user@Cyphon02:/opt$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
cb9572070104        dunbar/cyphon       "/bin/sh"           45 minutes ago      Up 34 minutes       8000/tcp            cyphon

Now, I've tried do telnet to port 8000 and I dont' have access 

user@Cyphon02:/opt$ telnet localhost 8000
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

I dont see nothing about this port with netstat, I try map the port with:

user@Cyphon02:/opt$ docker port cyphon 8000
Error: No public port '8000/tcp' published for cyphon

I don't know to do for starts this proyect....what else about this???

Any idea???

I want to start only Cyphon, I'm already set ELK on another machine.

please, help me.

Thanks

**Comment by santi10** [comment]
Also, I've set on file "conf.py" this:

HOST_SETTINGS = {
   'ALLOWED_HOSTS': ['example.com', '127.0.0.1'],
   'CORS_ORIGIN_WHITELIST': ['example.com', '127.0.0.1'],
}

I modified this config on "docker exec -it cyphon /bin/sh"

**Comment by chasepbrewer** [comment]
The docker image of Cyphon requires a PostgreSQL server in order to run. If it can't find a database to connect to, then it won't start the Gunicorn or Django development server on port 8000. In your case The Cyphondock docker compose file you've used in the past includes all these dependencies and more, but it sounds like you're trying to integrate it into a currently running ELK stack based on what you said in another issue. I put creating a docker compose file for that situation on my backlog of things to do.
