### ISSUE TITLE
Questions on initial data collection.

### ISSUE THREAD

**Issue by mgaulton** [dunbarcyber/cyphon#95]
I have my initial PoC loaded and prepopulated with the defaults. I was hoping for a "to set up this log source, do these steps" but i only found the one tutorial like that. 

I have the following data, that I can't seem to figure out how to "plug in" to the cyphon solution. 
1. Bro Logs - different host - needs filebeat or logstash to talk to cyphon box but how do i deploy the cyphon config to that host so that I don't need to manually build it.
2. Snort database - we have a database that normally gets populated by barnyard from the unified2 files. Can I consume these directly or must snort logs be plain text files?
3. Qualys cloud logs possibly through api? Anyone setup that up.

**Comment by censey** [comment]
Is this the tutorial you are referring to?  http://cyphon.readthedocs.io/en/latest/tutorials/logstash-tutorial.html

1.)  We ship bro NSM logs to Cyphon via filebeat.  You can set this up as you normally would any other logstash input.  

2.)  We are doing the same approach for Snort Alerts.  If you are using security onion or something you would have to dump them to a flat file and ship file filebeat.  It is far easier than converting the unified2 format.

3.) We have not tried Qualys but the API would need some development.  If they have a tutorial on exporting a JSON format, it would look like ingesting a .Nessus file.

**Comment by lhadjchikh** [comment]
To add to what @censey said, the configuration for handling Bro logs is in the [Logstash configs](https://github.com/dunbarcyber/cyphondock/tree/master/config-COPYME/logstash) included with Cyphondock. (This also includes some configs for plain text Snort logs).

On your remote hosts, you'll need to install and run Filebeat to send your Bro logs to your Logstash instance. We assume Logstash is running on your Cyphon host machine, but this doesn't have to be the case. Cyphon just needs to have a connection to the Elasticsearch and/or RabbitMQ instance where the logs are being sent, via the [Logstash output configuration](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/3-output.conf). You can configure Cyphon's Elasticsearch and RabbitMQ settings in [`config/env/cyphon.env`](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/env/cyphon.env) or [`config/cyphon/settings/conf.py`](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/cyphon/settings/conf.py).

For each type of Bro log, you'll need to set up a Filebeat prospector that labels the `document_type` appropriately, since this is what the [Logstash Bro filter](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/2-filter1-bro.conf) uses to identify the different logs.

**Comment by mgaulton** [comment]
@censey The tutorial was for snort ingesting from log files. I'll look at the one you linked.

1. I've never used filebeat. I'll have to read more, I have only ever done logstash against bro logs.

2. We have an inhouse sensor that writes unified. we do 5+ gigs of sustained traffic so text logs are expensive.

3. i'll have a look. we do some custom importing etc but i'm not sure if its json or not.

Thanks for the quick response.

**Comment by mgaulton** [comment]
@censey wait, that is the tutorial i saw :)

**Comment by lhadjchikh** [comment]
Maybe this could help? https://github.com/cleesmith/unifiedbeat

**Comment by mgaulton** [comment]
@lhadjchikh that just might. I'll have to take a closer look at it.

**Comment by mgaulton** [comment]
ops, wrong button

**Comment by lhadjchikh** [comment]
Also, check out the [example Filebeat config](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/beats/filebeat/filebeat.yml) in Cyphondock. :-)

**Comment by censey** [comment]
We have a similar in house sensor appliance which runs snort / bro.  In our case, these are remote sensors which run the Snort / Bro engines and filebeat.  They ship their output to an instance of Cyphon which hosts logstash and can query our Elastic cluster. 

We have Cyphon setup to process the snort and bro "intel" alerts. The rest of the content is sent to Elasticsearch (you know) for search.  In our use case, "http", "dns", etc are context look up's used by our analyst team while investigating a snort alert or intel event.

**Comment by mgaulton** [comment]
ours isn't distributed, it's a single node with a fat pipe to the externals. Sounds like i installed filebeat, it shoots the stuff over to the logstash instance, so i don't have to put / confg logstash on the remote node. I apparently was approaching it the old way :)

**Comment by censey** [comment]
That's right.  You can leverage all kinds of "beats" for different remote source types and populate the data in Cyphon or Elastic via logstash.  Once the content is in the system you can create context searches on "Related Data" which allows your team to pivot off of Cyphon alerts.

**Comment by lhadjchikh** [comment]
Closing this out, but feel free to reopen if you have any more questions.
